### LISTAR CLIENTE
GET http://localhost:8080/api/clientes/listar

### BUSCAR CLIENTE POR NOME OU ID
GET http://localhost:8080/api/clientes/buscaPorIdOuNome/1

### LEITURA DE CLIENTES POR NOME
GET http://localhost:8080/api/clientes/listar/Maria

### BUSCAR POR TEXTO
GET http://localhost:8080/api/clientes/buscarPorTexto/Maria

### CRIAR CLIENTE
POST http://localhost:8080/api/clientes
Content-Type: application/json

{
    "id": null,
    "nome": "EDuarda",
    "endereco": "Avenida Brasil",
    "cidade": {
        "id": 1
    }
}

### LISTAR CLIENTE POR NOME
GET http://localhost:8080/api/clientes/Maria


### ATUALIZAR CLIENTE
PUT http://localhost:8080/api/clientes/atualizar
Content-Type: application/json

{
    "id": 1,
    "nome": "Café",
    "endereco": "Virgilio de Rezende"
}

### DELETAR CLIENTE
DELETE http://localhost:8080/api/clientes/deletar/4

### Teste com ID
GET http://localhost:8080/api/clientes/buscarPorTexto?texto=1