###
GET http://localhost:8080/api/clientes/cpf/81

###
POST http://localhost:8080/api/clientes
Content-Type: application/json

{
    "id": 1,
    "nome": "Nicolas"
}

###
GET http://localhost:8080/api/clientes/listar


###
POST http://localhost:8080/api/clientes/criarCliente
Content-Type: application/json

{
    "id": 111,
    "nome": "Amanda"
}

###
DELETE http://localhost:8080/api/clientes/deletar/111

###
PUT http://localhost:8080/api/clientes/atualizar/94
Content-Type: application/json

{
    "id": 11,
    "nome": "Nicolas Drosdoski"
}