### LISTAR CLIENTE
GET http://localhost:8080/api/clientes/listar

### BUSCAR CLIENTE POR NOME OU ID
GET http://localhost:8080/api/clientes/buscarPorIdNome/1

### CRIAR CLIENTE
POST http://localhost:8080/api/clientes/criarCliente
Content-Type: application/json

{
    "id": null,
    "nome": "Carminha1",
    "endereco": "Avenida Brasil"
}

### LISTAR CLIENTE POR NOME
GET http://localhost:8080/api/clientes/Maria


### ATUALIZAR CLIENTE
PUT http://localhost:8080/api/clientes/atualizar
Content-Type: application/json

{
    "id": 1,
    "nome": "Café",
    "endereco": "Virgilio de Rezende"
}

### DELETAR CLIENTE
DELETE http://localhost:8080/api/clientes/deletar/4